from nmd.v1_s30_semantic_core import (
    S30_ATTENTION_LORA_PARAMETER_COUNT,
    S30_ATTENTION_TOTAL_PARAMETER_COUNT,
    S30_FFN_LORA_PARAMETER_COUNT,
    S30_FFN_TOTAL_PARAMETER_COUNT,
    S30_PROJECTION_PARAMETER_COUNT,
)


def test_s30_declared_arm_capacities():
    assert S30_ATTENTION_LORA_PARAMETER_COUNT==16384
    assert S30_PROJECTION_PARAMETER_COUNT==32768
    assert S30_ATTENTION_TOTAL_PARAMETER_COUNT==49152
    assert S30_FFN_LORA_PARAMETER_COUNT==20480
    assert S30_FFN_TOTAL_PARAMETER_COUNT==53248
